project_id = "emfbocpmphtftqcezaib"

[functions.sync-meta]
verify_jwt = false

[functions.ticto-webhook]
verify_jwt = false

[functions.ai-agent]
verify_jwt = false

[functions.webhook-lead]
verify_jwt = false

[functions.whatsapp-chats]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.whatsapp-contact-info]
verify_jwt = false

[functions.whatsapp-presence]
verify_jwt = false

[functions.uazapi-webhook]
verify_jwt = false

[functions.whatsapp-instance]
verify_jwt = false

[functions.sync-leads-from-sales]
verify_jwt = false

[functions.guru-webhook]
verify_jwt = false

[functions.eduzz-webhook]
verify_jwt = false

[functions.whatsapp-media]
verify_jwt = false

[functions.impersonate-user]
verify_jwt = false

[functions.wz-receiver]
verify_jwt = false

[functions.wz-executor]
verify_jwt = false

[functions.wz-scheduler]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false
