 SELECT t.id,
    t.source_platform AS platform,
    t.funnel_id,
    t.status,
    COALESCE(t.order_date, t.created_at) AS purchased_at,
    t.paid_amount / 100.0 AS revenue,
    t.product_name,
    t.product_id::text AS product_id,
    t.offer_name,
    t.payment_method,
    t.customer_name,
    t.customer_email,
    t.customer_phone,
    NULL::uuid AS unified_customer_id,
    t.meta_campaign_id,
    t.meta_adset_id,
    t.meta_ad_id,
    t.meta_campaign_name,
    t.meta_adset_name,
    t.meta_ad_name,
    t.utm_source,
    t.utm_campaign,
    t.utm_medium,
    t.utm_content,
    t.is_paid_traffic,
    t.ingestion_type,
    t.affiliate_name,
    t.affiliate_commission,
    NULL::text AS guru_account_slug,
    NULL::text AS guru_account_name
   FROM ticto_transactions t
  WHERE t.source_platform = 'ticto'::text AND t.product_name IS NOT NULL AND t.product_name <> ''::text
UNION ALL
 SELECT cp.id,
    cp.platform,
    cp.funnel_id,
    cp.status,
    cp.purchased_at,
    cp.gross_amount AS revenue,
    cp.product_name,
    cp.product_id,
    cp.offer_name,
    cp.payment_method,
    uc.full_name AS customer_name,
    uc.primary_email AS customer_email,
    uc.primary_phone AS customer_phone,
    cp.unified_customer_id,
    cp.meta_campaign_id,
    cp.meta_adset_id,
    cp.meta_ad_id,
    NULL::text AS meta_campaign_name,
    NULL::text AS meta_adset_name,
    NULL::text AS meta_ad_name,
    cp.utm_source,
    cp.utm_campaign,
    cp.utm_medium,
    cp.utm_content,
    cp.meta_campaign_id IS NOT NULL AS is_paid_traffic,
    cp.ingestion_type,
    cp.affiliate_name,
    cp.affiliate_commission,
    cp.guru_account_slug,
    ga.display_name AS guru_account_name
   FROM customer_purchases cp
     LEFT JOIN unified_customers uc ON uc.id = cp.unified_customer_id
     LEFT JOIN guru_accounts ga ON ga.account_slug = cp.guru_account_slug
  WHERE cp.platform <> 'ticto'::text AND cp.product_name IS NOT NULL AND cp.product_name <> ''::text;